#!/bin/sh
set -xeu

# Install dependencies
apt update
apt install -y \
	libebtree6-dev \
	libtokyocabinet-dev \
    liblzo2-dev \
    libglib2.0-dev \
    libpcre3-dev \
    libgcrypt-dev \
    libgpg-error-dev
