#!/bin/sh
set -xe

# Install dependencies
apt-get update
apt-get install -y \
	libebtree6-dev \
	libtokyocabinet-dev \
    liblzo2-dev \
    libglib2.0-dev \
    libpcre3-dev \
    libgcrypt-dev \
    libgpg-error-dev
